concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        lfs: false
    - continue-on-error: true
      name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@c00ea1b2ac047eaf7318275ac83a0cb846cea71a
      with:
        override-deps: 'rich>=9.5.1,<11.0.0

          '
        targets: tools/scripts/ansible/*-playbook.yml
  testprovision:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        lfs: false
    - continue-on-error: true
      name: Install Vagrant and Ansible
      run: brew install ansible
    - continue-on-error: true
      name: Prepare the provision
      run: (cd tools/scripts/ansible && ansible-galaxy install -r requirements.yml
        && ln -sv test-local-vars local-vars && vagrant validate)
    - continue-on-error: true
      env:
        VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
      name: Try the provision
      run: "(cd tools/scripts/ansible && vagrant up || ( ( echo \"# WARNING vagrant\
        \ failed\u2014we are ignoring the failure until https://unicode-org.atlassian.net/browse/CLDR-17297\
        \ \u2026 Try it manually.\" | tee -a $GITHUB_STEP_SUMMARY)  ; true ) )"
name: Ansible Lint
on:
  repository_dispatch:
    types: trigger-ga___ansible-lint.yml
