jobs:
  build:
    name: Run Checker
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: clone CLDR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false
        path: cldr
        ref: ${{ github.event.inputs.end-ref }}
    - continue-on-error: true
      name: clone ICU for tools
      uses: actions/checkout@v4
      with:
        lfs: false
        path: icu
        ref: ${{ github.event.inputs.tool-ref }}
        repository: ${{ github.event.inputs.tool-repository }}
    - continue-on-error: true
      env:
        CCC_HOST: cldr-smoke.unicode.org
        CCC_KNOWNHOSTS: ${{ secrets.CCC_KNOWNHOSTS }}
        CCC_PORT: 22
        CCC_USER: ${{ secrets.CCC_USER }}
        END_REF: ${{ github.event.inputs.end-ref }}
        FV: ${{ github.event.inputs.fix-version }}
        LV: ${{ github.event.inputs.last-version }}
        RSA_KEY_CCC: ${{ secrets.RSA_KEY_CCC }}
      name: Run Check and Publish
      run: 'echo "::group::Setup Checker"

        END_HASH=$(cd ${GITHUB_WORKSPACE}/cldr ; git rev-parse --short HEAD )

        REPORT="CLDR-Report-"$(date +"%Y-%m-%d")-v${FV}-${END_HASH}

        echo $REPORT

        cd icu/tools/commit-checker

        command -v pipenv >/dev/null 2>/dev/null || sudo pip3 install pipenv

        pipenv install -v

        pipenv install -v packaging || true

        echo "::endgroup::"

        echo "::group::Run Checker"

        pipenv run python3 check.py \

        --nocopyright \

        --jira-query "project=CLDR AND fixVersion=${FV}" \

        --repo-root ${GITHUB_WORKSPACE}/cldr \

        --fix-version ${FV} \

        --commit-metadata ${GITHUB_WORKSPACE}/cldr/.github/COMMIT_METADATA.md \

        --github-url https://github.com/unicode-org/cldr \

        --rev-range "release-${LV}..${END_REF}" > ${GITHUB_WORKSPACE}/${REPORT}.md

        echo "::endgroup::"

        echo "::group::Format .html"

        cd ${GITHUB_WORKSPACE}

        wc -l ${REPORT}.md

        npx -p markdown-to-html markdown --flavor gfm --title ${REPORT} ${REPORT}.md
        -c unicode-org/cldr README.md --stylesheet github-markdown.css > ${REPORT}.html

        echo "::endgroup::"

        echo "::group::Publish Report"

        echo "${RSA_KEY_CCC}" > ${HOME}/.key && chmod go= ${HOME}/.key

        echo "${CCC_KNOWNHOSTS}" > ${HOME}/.knownhosts && chmod go= ${HOME}/.knownhosts

        ln ${REPORT}.md CLDR_REPORT.md # use a fixed name for the publish step

        scp -o UserKnownHostsFile=${HOME}/.knownhosts -i ${HOME}/.key -P ${CCC_PORT}
        ${REPORT}.md ${REPORT}.html ${CCC_USER}@${CCC_HOST}:public_html/

        echo "::endgroup::"

        echo "Now go to https://cldr-smoke.unicode.org/cldrcc/${REPORT}.html"

        '
    - continue-on-error: true
      name: Upload CLDR_REPORT.md
      uses: actions/upload-artifact@v3
      with:
        name: commit-checker-report
        path: CLDR_REPORT.md
name: commit-checker
on:
  repository_dispatch:
    types: trigger-ga___commit-checker.yml
