concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        lfs: false
    - continue-on-error: true
      name: Cache local npm repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-nodetr-${{ hashFiles('tools/scripts/tr-archive/package-lock.json')
          }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-nodetr-

          nodetr-

          '
    - continue-on-error: true
      uses: nodenv/actions/node-version@v3
    - continue-on-error: true
      name: Run TR archiver
      run: cd tools/scripts/tr-archive/ && npm ci && npm run build
    - continue-on-error: true
      name: Run Kbd Charts
      run: cd docs/charts/keyboard && npm ci && npm run build
    - continue-on-error: true
      name: Upload tr35.zip
      uses: actions/upload-artifact@v3
      with:
        name: tr35-spec
        path: tools/scripts/tr-archive/tr35.zip
    - continue-on-error: true
      name: Run TR link extractor (experimental)
      run: cd tools/scripts/tr-archive/ && npm run extract-link-targets || (echo Warning,
        please fix these ; true)
    - continue-on-error: true
      name: Lint Markdown
      run: npx markdownlint-cli *.md {specs,docs}/*.md $(find .github -name '*.md')
        || (echo Warning, please fix these ; true)
    - continue-on-error: true
      name: Note any changes
      run: git status ; git diff
    - continue-on-error: true
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.2
    - continue-on-error: true
      name: Build Jekyll part of the site
      run: 'gem install bundler github-pages kramdown-parser-gfm  # should pull in
        jekyll, etc.

        jekyll build -s docs -d _site

        '
    - continue-on-error: true
      name: Rearrange stuff
      run: cp -vr tools/scripts/tr-archive/dist/* ./_site/ldml/ && cp tools/scripts/tr-archive/reports-v2.css
        ./_site/
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      name: Deploy to GitHub Pages (main)
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        branch: gh-pages
        build_dir: _site
        commit_message: CLDR-00000 Automated Build of Pages
    - continue-on-error: true
      env:
        CCC_HOST: cldr-smoke.unicode.org
        CCC_KNOWNHOSTS: ${{ secrets.CCC_KNOWNHOSTS }}
        CCC_PORT: 22
        CCC_USER: ${{ secrets.CCC_USER }}
        RSA_KEY_CCC: ${{ secrets.RSA_KEY_CCC }}
      name: Deploy to Smoketest
      run: 'echo "::group::Publish HTML"

        echo "${RSA_KEY_CCC}" > ${HOME}/.key && chmod go= ${HOME}/.key

        echo "${CCC_KNOWNHOSTS}" > ${HOME}/.knownhosts && chmod go= ${HOME}/.knownhosts

        rsync -cav --delete-after -e "ssh -o UserKnownHostsFile=${HOME}/.knownhosts
        -i ${HOME}/.key -p ${CCC_PORT}" ./_site/ ${CCC_USER}@${CCC_HOST}:spec/$(basename
        ${GITHUB_REF_NAME})/

        echo "::endgroup::"

        echo "Now go to https://cldr-smoke.unicode.org/spec/"$(basename ${GITHUB_REF_NAME})

        '
      shell: bash
name: Publish to gh-pages
on:
  repository_dispatch:
    types: trigger-ga___gh-pages.yml
