jobs:
  fetest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        lfs: false
    - continue-on-error: true
      uses: nodenv/actions/node-version@v3
    - continue-on-error: true
      name: Cache webpack
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-webpack-${{ hashFiles('tools/cldr-apps/package*') }}-${{
          hashFiles('tools/cldr-apps/src/**') }}
        path: tools/cldr-apps/target/webpack_cache
        restore-keys: '${{ runner.os }}-webpack-

          webpack-

          '
    - continue-on-error: true
      name: Cache npm repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-lint-${{ hashFiles('.github/workflows/js.yml') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-lint-

          lint-

          '
    - continue-on-error: true
      name: Prepare JS tests
      run: (cd tools/cldr-apps/js && npm ci)
    - continue-on-error: true
      name: Run JS tests
      run: (cd tools/cldr-apps/js && npm t)
      timeout-minutes: 10
    - continue-on-error: true
      name: Run Webpack production build
      run: (cd tools/cldr-apps/js && npm run build)
name: JavaScript Tests
on:
  repository_dispatch:
    types: trigger-ga___js.yml
