jobs:
  keyboard-compile:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event.inputs.git-ref == ''
      name: Clone Repository
      uses: actions/checkout@v4
      with:
        lfs: false
    - continue-on-error: true
      if: github.event.inputs.git-ref != ''
      name: Clone Repository (manual ref)
      uses: actions/checkout@v4
      with:
        lfs: false
        ref: ${{ github.event.inputs.git-ref }}
    - continue-on-error: true
      name: Cache local npm repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-nodekbd-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-nodekbd-

          nodekbd-

          '
    - continue-on-error: true
      name: Install kmc
      run: npm install -g @keymanapp/kmc@beta
    - continue-on-error: true
      name: Compile Keyboards
      run: kmc --error-reporting build keyboards/3.0/*.xml
    - continue-on-error: true
      name: Run Kbd Charts
      run: cd docs/charts/keyboard && npm ci && npm run build
name: kbd-check
on:
  repository_dispatch:
    types: trigger-ga___keyboard.yml
