jobs:
  mvn-deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        lfs: false
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('tools/**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build with Maven
      run: 'mvn -s .github/workflows/mvn-settings.xml -B compile install package --file
        tools/pom.xml -DskipTests=true

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: set version to generic number
      run: 'mvn -s .github/workflows/mvn-settings.xml --file tools/pom.xml versions:set
        -DnewVersion=0.0.0-SNAPSHOT-$(echo ${GITHUB_SHA} | cut -c1-10)

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.repository == 'unicode-org/cldr'
      name: Upload to GitHub maven
      run: 'mvn -s .github/workflows/mvn-settings.xml  --file tools/pom.xml source:jar
        deploy

        '
name: cldr-mvn-deploy
on:
  repository_dispatch:
    types: trigger-ga___maven-release.yml
