jobs:
  build:
    name: Build for Staging
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone Repository (Custom Ref)
      uses: actions/checkout@v4
      with:
        lfs: false
        ref: ${{ github.event.inputs.git-ref }}
        repository: ${{ github.event.inputs.repo }}
    - continue-on-error: true
      id: tagname
      name: Calculate Tag Name
      run: 'echo "::set-output name=tag::$(env TZ=UTC date +''staging/%Y-%m-%d-%H%Mz'')"

        '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('tools/**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Cache local npm repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-node-

          node-

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build with Maven
      run: 'mvn -s .github/workflows/mvn-settings.xml -B compile install package --file
        tools/pom.xml -DskipTests=true

        '
    - continue-on-error: true
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_SITE: ${{ secrets.DATADOG_SITE }}
      name: DataDog sourcemap upload
      run: npx --package=@datadog/datadog-ci datadog-ci sourcemaps upload tools/cldr-apps/src/main/webapp/dist/
        --minified-path-prefix=/cldr-apps/dist/ --release-version=r${{ github.event.inputs.git-ref
        }} --service=surveytool
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build liberty server
      run: 'mvn -s .github/workflows/mvn-settings.xml -B  -pl cldr-apps liberty:create
        liberty:deploy liberty:package -Dinclude=usr --file tools/pom.xml -DskipTests=true

        '
    - continue-on-error: true
      name: Cleanup liberty server
      run: 'zip tools/cldr-apps/target/cldr-apps.zip  -d  wlp/usr/servers/cldr/apps/expanded/\*

        '
    - continue-on-error: true
      name: Upload cldr-apps.zip
      uses: actions/upload-artifact@v3
      with:
        name: cldr-apps-server
        path: tools/cldr-apps/target/cldr-apps.zip
  deploy:
    name: Deploy to Staging
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download cldr-apps.zip
      uses: actions/download-artifact@v3
      with:
        name: cldr-apps-server
    - continue-on-error: true
      env:
        DEPLOY_REPO: ${{ github.event.inputs.repo }}
        DEPLOY_SHA: ${{ github.event.inputs.git-ref }}
        OVERRIDE: ${{ github.event.inputs.override }}
        RSA_KEY_SURVEYTOOL: ${{ secrets.RSA_KEY_SURVEYTOOL }}
        STAGING_HOST: ${{ secrets.STAGING_HOST }}
        STAGING_KNOWNHOSTS: ${{ secrets.STAGING_KNOWNHOSTS }}
        STAGING_PORT: ${{ secrets.STAGING_PORT }}
      name: Deploy to st
      run: 'echo "${RSA_KEY_SURVEYTOOL}" > .key && chmod go= .key

        echo "${STAGING_KNOWNHOSTS}" > .knownhosts && chmod go= .knownhosts

        ssh -C -o UserKnownHostsFile=.knownhosts -i .key -p ${STAGING_PORT} surveytool@${STAGING_HOST}
        bash /usr/local/bin/deploy-to-openliberty.sh < cldr-apps.zip --repo "${DEPLOY_REPO}"
        ${DEPLOY_SHA} ${OVERRIDE}

        '
      shell: bash
name: staging
on:
  repository_dispatch:
    types: trigger-ga___staging.yml
